name: ektm
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.10.2
  lucide_icons: ^0.257.0 # (Icons)
  iconify_flutter: ^0.0.7 # (Icons)
  video_player: ^2.7.0

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 #Fonts Google
  flutter_native_splash: ^2.3.9 # Untuk splash screen native
  go_router: ^12.0.0 # Untuk navigasi lebih fleksibel
  provider: ^6.1.2 # State management (jika diperlukan)
  shared_preferences: ^2.2.2 # Untuk menyimpan preferensi pengguna seperti tema
  flutter_bloc: ^8.1.3 # Untuk state management berbasis BLoC (opsional)
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  mobile_scanner: ^3.2.0
  logging: ^1.2.0
  qr_flutter: ^4.0.0
  carousel_slider: 4.1.1
  google_maps_flutter: ^2.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/videos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_native_splash:
  color: "#020E60" # Warna background splash screen
  image: assets/images/logo_ektm.png # Path logo kamu
  android: true
  ios: true
  android_gravity: center # Letak logo (opsional)
  ios_content_mode: center # Letak logo di iOS (opsional)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_ektm.png"
  adaptive_icon_background: "#020E60"
  adaptive_icon_foreground: "assets/images/logo_ektm.png"
